# GitHub workflow to get and update the coverage report.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

name: codecov

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  coverage:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "pypy3.8", "3.9", "pypy3.9", "3.10", "pypy3.10", "3.11", "3.12"]
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    env:
      OS_USE: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python_version }}
    steps:
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python_version }}

    - uses: actions/checkout@main

    - name: Build & Install dependencies
      run: |
        pip install .
        pip install -r requirements-dev.txt

    - name: Clean up build files
      run: |
        if [ -d build/ ]; then
          rm -rf build/
        fi
      shell: bash

    - name: Generate coverage report
      run: |
        python run_tests.py --verbose --cov --no-color
        coverage xml

    - name: Upload coverage report
      uses: codecov/codecov-action@main
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS_USE,PYTHON_VERSION
