# GitHub workflow to get and update the coverage report.
#
# Copyright (C) 2023  Cao Bo Wen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: coverage

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  coverage:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    env:
      OS_USE: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python_version }}
    runs-on: ${{ env.OS_USE }}
    steps:
    - uses: actions/setup-python@main
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - uses: actions/checkout@main

    - name: Install dependencies
      run: pip install -r requirements-dev.txt

    - name: Generate coverage report
      run: |
        python run_tests.py --verbose --cov
        coverage xml

    - name: Upload coverage report
      uses: codecov/codecov-action@main
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS_USE,PYTHON_VERSION
