# GitHub workflow to run tests.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

name: build & test

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "pypy3.8", "3.9", "pypy3.9", "3.10", "pypy3.10", "3.11", "3.12"]
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python_version }}

    - uses: actions/checkout@main

    - name: Build test & Install dependencies
      run: pip install .

    - name: Run tests
      run: python run_tests.py --verbose
