name: test

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: ["windows-latest", "macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        cd ../
        python PyCompatibility/run_tests.py
